use std::cmp::max;
use std::iter::repeat_n;
use std::ops::Mul;
use ark_ff::PrimeField;
use crate::multilinear::MultivariatePoly;
use crate::composite::{Composite, OP as COMPOSITE_OP};
use circuit::circuit::{ Circuit, CIRCUIT_OP, Gate};
use prime_polynomail::DensePolynomial;
use transcript::transcript::{Transcript, HashTrait};
use std::marker::PhantomData;